### ISSUE TITLE
Very Advanced - Audio Source setting screen does not fit

### ISSUE THREAD

**Issue by ionise** [TheCacophonyProject/cacophonometer#17] opened 2019-01-29 05:25 UTC
On a small phone screen the last option for Audio Source falls off the bottom of the screen and cannot be viewed.
The last option should show VOICE RECOGNITION but cannot be read.
Screenshot https://photos.app.goo.gl/gKHRhyxaoxMfyDAw9

**Comment by timhot** [comment] 2019-01-29 23:51
thanks for the feedback - I've put the radio buttons in a scroll view..

**Comment by timhot** [comment] 2019-01-30 00:40
fixed in https://github.com/TheCacophonyProject/cacophonometer/releases/tag/1.3.5Beta

**Comment by mjs** [comment] 2019-03-25 02:26
Can this be closed or are we waiting for confirmation that the problem is truly fixed?

**Comment by timhot** [comment] 2019-04-28 04:50
truly fixed

**Closed as completed by timhot** 2019-04-28 04:50 UTC
Labels: bug
